spring:
  datasource:
    url: jdbc:mysql://mex.3-gd.com:3308/doc_warehouse?serverTimezone=CST&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: doc_warehouse
    password: doc_warehouse@2021
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  mapper-locations: mappers/*.xml


security:
  jwt:
    sign-secret-key: tom-debug