spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/doc_warehouse?serverTimezone=CST&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: ser-dev-root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  mapper-locations: mappers/*.xml


security:
  jwt:
    sign-secret-key: tom-test